---
- name: "[cron] Ensure Lynis config directory {{ lynis_config_directory }} exists"
  file:
    path: "{{ lynis_config_directory }}"
    state: directory
    owner: root
    group: root
    mode: 0750

- name: "[cron] Ensure Lynis log directory {{ lynis_log_directory }} exists"
  file:
    path: "{{ lynis_log_directory }}"
    state: directory
    owner: root
    group: "{{ lynis_log_group }}"
    mode: 0750

- name: "[cron] Configure Lynis log rotation"
  template:
    src: logrotate.j2
    dest: "{{ lynis_config_directory }}/logrotate.conf"
    owner: root
    group: root
    mode: 0644

- name: "[cron] Ensure Lynis cron script exists"
  template:
    src: cron.sh.j2
    dest: "{{ lynis_config_directory }}/cron.sh"
    owner: root
    group: root
    mode: 0750

- name: "[cron] Configure Lynis cron task"
  cron:
    name: Run Lynis
    cron_file: lynis
    month: "{{ lynis_cron_month }}"
    day: "{{ lynis_cron_day }}"
    weekday: "{{ lynis_cron_weekday }}"
    hour: "{{ lynis_cron_hour }}"
    minute: "{{ lynis_cron_minute }}"
    user: root
    job: "{{ lynis_config_directory }}/cron.sh"

- name: "[cron] initial audit run"
  command: "{{ lynis_config_directory }}/cron.sh"
  args:
    chdir: /
  when: lynis_cron_initial_run and ( _lynis_installed_version.stdout != lynis_version )
