---
- name: "Prepare Lynis directory {{ lynis_directory }}"
  ansible.builtin.file:
    state: directory
    path: "{{ lynis_directory }}"
    owner: root
    group: root
    mode: 0755


- name: "Check installed version"
  ansible.builtin.shell: "cat {{ lynis_directory }}/.version || echo ''"
  changed_when: false
  register: _lynis_installed_version

- name: "Install lynis"
  when: _lynis_installed_version.stdout != lynis_version
  block:
    - name: "Make temporary directory for installation"
      ansible.builtin.tempfile:
        state: directory
        suffix: lynis
      register: _temp
      changed_when: true

    - name: "Download Lynis {{ lynis_version }}"
      ansible.builtin.get_url:
        url: "https://cisofy.com/files/lynis-{{ lynis_version }}.tar.gz"
        dest: "{{ _temp.path }}/lynis-{{ lynis_version }}.tar.gz"
        checksum: "sha256:{{ lynis_version_sha256sum }}"
        mode: '640'

    - name: "Extract Lynis tarball"
      ansible.builtin.unarchive:  # noqa 208 (see also https://github.com/infothrill/ansible-role-lynis/issues/55)
        src: "{{ _temp.path }}/lynis-{{ lynis_version }}.tar.gz"
        dest: "{{ _temp.path }}"
        creates: "{{ _temp.path }}/lynis"
        copy: false
        owner: root
        group: root

    - name: "Create .version file"
      ansible.builtin.copy:
        content: "{{ lynis_version }}"
        dest: "{{ _temp.path }}/lynis/.version"
        owner: root
        group: root
        mode: 0644

    - name: "Copy Lynis into place"
      ansible.builtin.command: cp -rT {{ _temp.path }}/lynis {{ lynis_directory }}  # noqa no-changed-when

    - name: "Delete temporary directory"
      ansible.builtin.file:
        state: absent
        path: "{{ _temp.path }}"
