---
- name: "[install] Prepare Lynis directory {{ lynis_directory }}"
  file:
    state: directory
    path: "{{ lynis_directory }}"
    owner: root
    group: root
    mode: 0755


- name: "[install] check installed version"
  shell: "cat {{ lynis_directory }}/.version || echo ''"
  changed_when: false
  register: _lynis_installed_version

- block:
    - name: "[install] make temporary directory for installation"
      tempfile:
        state: directory
        suffix: lynis
      register: _temp
      changed_when: true

    - name: "[install] Download Lynis {{ lynis_version }}"
      get_url:
        url: "https://cisofy.com/files/lynis-{{ lynis_version }}.tar.gz"
        dest: "{{ _temp.path }}/lynis-{{ lynis_version }}.tar.gz"
        sha256sum: "{{ lynis_version_sha256sum }}"

    - name: "[install] Extract Lynis tarball"
      unarchive:
        src: "{{ _temp.path }}/lynis-{{ lynis_version }}.tar.gz"
        dest: "{{ _temp.path }}"
        creates: "{{ _temp.path }}/lynis"
        copy: false
        owner: root
        group: root
        mode: '750'

    - name: "[install] create .version file"
      copy:
        content: "{{ lynis_version }}"
        dest: "{{ _temp.path }}/lynis/.version"
        owner: root
        group: root
        mode: 0644

    - name: "[install] copy Lynis into place"
      command: cp -rT {{ _temp.path }}/lynis {{ lynis_directory }}

    - name: "[install] delete temporary directory"
      file:
        state: absent
        path: "{{ _temp.path }}"

  when: _lynis_installed_version.stdout != lynis_version
