---
- name: "[install] Prepare Lynis directory {{ lynis_directory }}"
  file:
    state: directory
    path: "{{ lynis_directory }}"
    owner: root
    group: root
    mode: 0755


- name: "[install] check installed version"
  shell: "cat {{ lynis_directory }}/.version || echo ''"
  changed_when: false
  register: _lynis_installed_version

- block:
    - name: "[install] make temporary directory for installation"
      command: mktemp -d
      register: _temp
      changed_when: true

    - name: "[install] Download Lynis {{ lynis_version }}"
      get_url:
        url: "https://cisofy.com/files/lynis-{{ lynis_version }}.tar.gz"
        dest: "{{ _temp.stdout }}/lynis-{{ lynis_version }}.tar.gz"
        sha256sum: "{{ lynis_version_sha256sum }}"

    - name: "[install] Extract Lynis tarball"
      unarchive:
        src: "{{ _temp.stdout }}/lynis-{{ lynis_version }}.tar.gz"
        dest: "{{ _temp.stdout }}"
        creates: "{{ _temp.stdout }}/lynis"
        copy: false
        owner: root
        group: root

    - name: "[install] create .version file"
      copy:
        content: "{{ lynis_version }}"
        dest: "{{ _temp.stdout }}/lynis/.version"
        owner: root
        group: root
        mode: 0644

    - name: "[install] copy Lynis into place"
      command: cp -rT {{ _temp.stdout }}/lynis {{ lynis_directory }}

    - name: "[install] delete temporary directory"
      file:
        state: absent
        path: "{{ _temp.stdout }}"

  when: _lynis_installed_version.stdout != lynis_version
