---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint --exclude molecule  --offline
platforms:
  - name: lynis-ubuntu-2204
    image: ubuntu:22.04
  - name: lynis-ubuntu-2404
    image: ubuntu:24.04
  - name: lynis-debian-12-bookworm
    image: debian:bookworm
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
