---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: lynis-ubuntu-1404
    image: ubuntu:14.04
  - name: lynis-ubuntu-1604
    image: ubuntu:16.04
  - name: lynis-ubuntu-1804
    image: ubuntu:18.04
  - name: lynis-debian-stretch
    image: debian:stretch
  - name: lynis-debian-jessie
    image: debian:jessie
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
