---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint --exclude molecule  --offline
platforms:
  - name: lynis-ubuntu-1604
    image: ubuntu:16.04
  - name: lynis-ubuntu-1804
    image: ubuntu:18.04
  - name: lynis-ubuntu-2004
    image: ubuntu:20.04
  - name: lynis-debian-stretch
    image: debian:stretch
  - name: lynis-debian-buster
    image: debian:buster
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
