---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint --exclude molecule  --offline
platforms:
  - name: lynis-ubuntu-1804
    image: ubuntu:18.04
  - name: lynis-ubuntu-2004
    image: ubuntu:20.04
  - name: lynis-ubuntu-2204
    image: ubuntu:22.04
  - name: lynis-debian-buster
    image: debian:buster
  - name: lynis-debian-11-bullseye
    image: debian:bullseye
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
