---
- name: Prepare
  hosts: all
  gather_facts: false
  post_tasks:
    # Some recent debian based docker images do not have /etc/cron.d .
    # For the purpose of this test, we assume the target environment
    # has cron, thus we install it:
    - name: "Ensure cron is installed"
      apt:
        name: cron
        state: present
        update_cache: true
